# Generated by Django 4.0.4 on 2022-05-20 18:20

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('desc', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('image', models.FileField(upload_to=api.models.upload)),
                ('datestamp', models.CharField(default=None, max_length=225)),
                ('timestamp', models.CharField(default=None, max_length=225)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
