# Generated by Django 4.0.4 on 2022-05-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_datestamp_alter_product_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
