# Generated by Django 4.0.4 on 2022-05-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_product_user_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Total_Price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
