# Generated by Django 4.0.4 on 2022-05-26 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cart_total_price_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
