# Generated by Django 4.0.4 on 2022-05-26 13:32

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_image',
            field=models.FileField(default=1, upload_to=api.models.upload),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='product_title',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
    ]
