# Generated by Django 4.0.4 on 2022-05-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_cart_product_image_cart_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
