# Generated by Django 4.0.4 on 2022-05-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_cart_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_image',
            field=models.URLField(default=None),
        ),
    ]
