# Generated by Django 4.0.4 on 2022-05-27 11:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_product_uuid_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
